export const mapping = new Map([
	[`(male, open)`, ["gopen"]],
	[`(female, open)`, ["lopen", "gopen"]],
	[`(male, sc)`, ["gopen", "gsc"]],
	[`(female, sc)`, ["lopen", "gopen", "lsc", "gsc"]],
	["(male, st)", ["gopen", "st"]],
	["(female, st)", ["lopen", "gopen", "lst", "gst"]],
	["(male, dt/vj)", ["gopen", "gdt/vj"]],
	["(female, dt/vj)", ["lopen", "gopen", "ldt/vj", "gdt/vj"]],
	["(male, nt-b)", ["gopen", "gnt-b"]],
	["(female, nt-b)", ["lopen", "gopen", "lnt-b", "gnt-b"]],
	["(male, nt-c)", ["gopen", "gnt-c"]],
	["(female, nt-c)", ["lopen", "gopen", "lnt-c", "gnt-c"]],
	["(male, nt-d)", ["gopen", "gnt-d"]],
	["(female, nt-d)", ["lopen", "gopen", "lnt-d", "gnt-d"]],
	["(male, obc)", ["gopen", "gobc"]],
	["(female, obc)", ["lopen", "gopen", "lobc", "gobc"]],

	// ["(male, sbc)", ["gopen", "gxx"]],
	["(male, sbc)", ["gopen", "gsc", "gst", "gdt/vj", "gnt-b", "gnt-c", "gnt-d", "gobc", "gdt/vj"]],
	// ["(female, sbc)", ["lopen", "gopen", "lxx", "gxx"]],
	["(female, sbc)", ["lopen", "gopen", "lsc", "lst", "ldt/vj", "lnt-b", "lnt-c", "lnt-d", "lobc", "ldt/vj", "gsc", "gst", "gdt/vj", "gnt-b", "gnt-c", "gnt-d", "gobc", "gdt/vj"]],

	["(male, pwdopen)", ["pwdopen", "gopen"]],
	["(female, pwdopen)", ["pwdopen", "lopen", "gopen"]],
	["(male, pwdsc)", ["pwdopen", "gopen", "pwdsc", "gsc"]],
	["(female, pwdsc)", ["pwdopen", "lopen", "gopen", "pwdsc", "lsc", "gsc"]],
	["(male, pwdst)", ["pwdopen", "gopen", "pwdst", "gst"]],
	["(female, pwdst)", ["pwdopen", "lopen", "gopen", "pwdst", "lst", "gst"]],
	["(male, pwddt/vj)", ["pwdopen", "gopen", "pwddt/vj", "gdt/vj"]],
	["(female, pwddt/vj)", ["pwdopen", "lopen", "gopen", "pwddt/vj", "ldt/vj", "gdt/vj"]],

	// page 2
	["(male, pwdnt-b)", ["pwdopen", "gopen", "pwdnt-b", "gnt-b"]],
	["(female, pwdnt-b)", ["pwdopen", "lopen", "gopen", "pwdnt-b", "lnt-b", "gnt-b"]],
	["(male, pwdnt-c)", ["pwdopen", "gopen", "pwdnt-c", "gnt-c"]],
	["(female, pwdnt-c)", ["pwdopen", "lopen", "gopen", "pwdnt-c", "lnt-c", "gnt-c"]],
	["(male, pwdnt-d)", ["pwdopen", "gopen", "pwdnt-d", "gnt-d"]],
	["(female, pwdnt-d)", ["pwdopen", "lopen", "gopen", "pwdnt-d", "lnt-d", "gnt-d"]],
	["(male, pwdobc)", ["pwdopen", "gopen", "pwdobc", "gobc"]],
	["(female, pwdobc)", ["pwdopen", "lopen", "gopen", "pwdobc", "lobc", "gobc"]],
	["(male, defopen)", ["defopen", "gopen"]],
	["(female, defopen)", ["defopen", "lopen", "gopen"]],
	["(male, defsc)", ["defopen", "gopen", "defsc", "gsc"]],
	["(female, defsc)", ["defopen", "lopen", "gopen", "defsc", "lsc", "gsc"]],
	["(male, defst)", ["defopen", "gopen", "defst", "gst"]],
	["(female, defst)", ["defopen", "lopen", "gopen", "defst", "lst", "gst"]],
	["(male, defdt/vj)", ["defopen", "gopen", "defdt/vj", "gdt/vj"]],
	["(female, defdt/vj)", ["defopen", "lopen", "gopen", "defdt/vj", "ldt/vj", "gdt/vj"]],
	["(male, defnt-b)", ["defopen", "gopen", "defnt-b", "gnt-b"]],
	["(female, defnt-b)", ["defopen", "lopen", "gopen", "defnt-b", "lnt-b", "gnt-b"]],
	["(male, defnt-c)", ["defopen", "gopen", "defnt-c", "gnt-c"]],
	["(female, defnt-c)", ["defopen", "lopen", "gopen", "defnt-c", "lnt-c", "gnt-c"]],
	["(male, defnt-d)", ["defopen", "gopen", "defnt-d", "gnt-d"]],
	["(female, defnt-d)", ["defopen", "lopen", "gopen", "defnt-d", "lnt-d", "gnt-d"]],

	// page 3
	["(male, defobc)", ["defopen", "gopen", "defobc", "gobc"]],
	["(female, defobc)", ["defopen", "lopen", "gopen", "defobc", "lobc", "gobc"]],
	["(male, orphan)", ["orphan", "gopen"]],
	["(female, orphan)", ["orphan", "lopen", "gopen"]],
]);