export const universities = [
	"Rashtrasant Tukadoji Maharaj Nagpur University",
	"Dr. Babasaheb Ambedkar Marathwada University",
	"Dr. Babasaheb Ambedkar Technological University,Lonere",
	"Gondwana University",
	"Kavayitri Bahinabai Chaudhari North Maharashtra University, Jalgaon",
	"Mumbai University",
	"Punyashlok Ahilyadevi Holkar Solapur University",
	"Sant Gadge Baba Amravati University",
	"Shivaji University",
	"SNDT Women's University",
	"Unitary Public University of Government of Maharashtra",
	"Swami Ramanand Teerth Marathwada University, Nanded",
	"Savitribai Phule Pune University",
];
